'use client';

import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';

export interface InferenceNoticeDialogProps {
  /** Called when the user explicitly acknowledges the notice. */
  onAcknowledge: () => void;
}

// Inline sparkle — matches the SVG-only icon discipline (no emoji as icons).
function SparkleIcon({ size = 20 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden
    >
      <path d="M12 3l1.8 4.9L18.7 9 13.8 10.8 12 15.7l-1.8-4.9L5.3 9l4.9-1.1z" />
      <path d="M19 14l.7 1.8L21.5 16.5l-1.8.7L19 19l-.7-1.8L16.5 16.5l1.8-.7z" />
    </svg>
  );
}

/**
 * First-render disclaimer that the 3D model is AI-inferred from the user's
 * photos. Acknowledgment-required: there is no close X, no tap-outside, and no
 * auto-fade — the user must press the primary button to continue. This replaces
 * the old auto-fading badge, which new users dismissed as unimportant. Styled to
 * match RefundRequestDialog so the studio's two new-account notices feel like one
 * deliberate system, not two throwaway toasts.
 */
export default function InferenceNoticeDialog({ onAcknowledge }: InferenceNoticeDialogProps) {
  const [visible, setVisible] = useState(false);
  const [closing, setClosing] = useState(false);
  const buttonRef = useRef<HTMLButtonElement>(null);

  // Fade in on mount (two RAFs so the transition starts from the hidden state).
  useEffect(() => {
    const id = requestAnimationFrame(() => requestAnimationFrame(() => setVisible(true)));
    return () => cancelAnimationFrame(id);
  }, []);

  // Move focus to the acknowledge button so keyboard users have an obvious,
  // single way forward (the button is the deliberate escape route).
  useEffect(() => {
    const t = setTimeout(() => buttonRef.current?.focus(), 360);
    return () => clearTimeout(t);
  }, []);

  const acknowledge = () => {
    if (closing) return;
    setClosing(true);
    setTimeout(onAcknowledge, 320); // let the fade-out play before the parent unmounts us
  };

  const shown = visible && !closing;

  return createPortal(
    <div
      data-testid="inference-notice-backdrop"
      className="fixed inset-0 z-[10040] flex items-center justify-center"
      style={{
        background: shown ? 'rgba(0,0,0,0.6)' : 'rgba(0,0,0,0)',
        transition: 'background 320ms ease',
        pointerEvents: shown ? 'auto' : 'none',
      }}
      // Intentionally no onClick-to-dismiss: this notice must be acknowledged.
    >
      <div
        role="alertdialog"
        aria-modal="true"
        aria-labelledby="inference-notice-title"
        className="relative flex flex-col gap-5 rounded-3xl"
        style={{
          background: 'var(--cream)',
          border: '1px solid rgba(42,32,26,0.1)',
          boxShadow: '0 32px 90px -16px rgba(0,0,0,0.5)',
          padding: '40px 44px 36px',
          maxWidth: 460,
          width: 'calc(100vw - 40px)',
          opacity: shown ? 1 : 0,
          transform: shown ? 'translateY(0) scale(1)' : 'translateY(14px) scale(0.98)',
          transition: 'opacity 320ms ease, transform 360ms cubic-bezier(.2,.85,.2,1)',
        }}
      >
        <div className="flex flex-col gap-3">
          <span
            className="flex items-center justify-center rounded-2xl"
            style={{
              width: 44,
              height: 44,
              background: 'color-mix(in srgb, var(--tomato) 14%, transparent)',
              color: 'var(--tomato)',
            }}
          >
            <SparkleIcon />
          </span>
          <div className="flex flex-col gap-1">
            <span className="font-mono text-[10px] uppercase tracking-[0.22em] text-[var(--smoke)]">
              How your model is made
            </span>
            <h2
              id="inference-notice-title"
              className="font-display italic text-[var(--ink)]"
              style={{ fontSize: 26, fontWeight: 600, lineHeight: 1.15 }}
            >
              Built from your photos
            </h2>
          </div>
        </div>

        <p className="font-sans text-[14px] text-[var(--char)] leading-relaxed">
          Your 3D model is generated by AI from the photos you gave us. Expect a great
          likeness &mdash; but some details are our best guess, not an exact measurement.
          Use it as a reference to bring to your barber.
        </p>

        <div className="flex flex-col pt-1">
          <button
            ref={buttonRef}
            onClick={acknowledge}
            className="w-full font-sans text-[14px] font-semibold rounded-xl py-3 transition-colors"
            style={{ background: 'var(--ink)', color: 'var(--cream)', border: 'none', cursor: 'pointer' }}
          >
            Got it &mdash; show me my model
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );
}
