import { describe, it, expect } from 'vitest';
import { readdirSync } from 'node:fs';
import path from 'node:path';
import {
  HAIRSTYLES,
  TRENDING_CUTS,
  hairstyleBySlug,
  isHairstyleSlug,
  slugForCut,
} from './hairstyles';

const PREVIEW_DIR = path.resolve(__dirname, '../../public/hair-previews');

function previewSlugsOnDisk(): string[] {
  return readdirSync(PREVIEW_DIR)
    .filter((file) => file.endsWith('.png'))
    .map((file) => file.replace(/\.png$/, ''));
}

describe('slugForCut', () => {
  it('lowercases and hyphenates, collapsing punctuation runs', () => {
    expect(slugForCut('low taper fade, textured fringe')).toBe('low-taper-fade-textured-fringe');
    expect(slugForCut('C-curl perm, shoulder length')).toBe('c-curl-perm-shoulder-length');
    expect(slugForCut('buzz cut, clean line-up')).toBe('buzz-cut-clean-line-up');
  });

  it('never leaves a leading or trailing hyphen', () => {
    expect(slugForCut('  ,messy fade, ')).toBe('messy-fade');
  });
});

describe('the catalog', () => {
  it('has both gendered pools, and every cut lands in exactly one', () => {
    expect(TRENDING_CUTS.mens.length).toBeGreaterThan(0);
    expect(TRENDING_CUTS.womens.length).toBeGreaterThan(0);
    expect(TRENDING_CUTS.mens.length + TRENDING_CUTS.womens.length).toBe(HAIRSTYLES.length);
  });

  it('has unique slugs and labels', () => {
    expect(new Set(HAIRSTYLES.map((c) => c.slug)).size).toBe(HAIRSTYLES.length);
    expect(new Set(HAIRSTYLES.map((c) => c.label)).size).toBe(HAIRSTYLES.length);
  });

  it('gives every cut a non-empty description', () => {
    for (const cut of HAIRSTYLES) {
      expect(cut.desc.length, `${cut.label} has no description`).toBeGreaterThan(20);
    }
  });

  it('looks up by slug and rejects unknown slugs', () => {
    expect(hairstyleBySlug('blowout-taper')?.label).toBe('blowout taper');
    expect(hairstyleBySlug('not-a-real-cut')).toBeUndefined();
    expect(isHairstyleSlug('blowout-taper')).toBe(true);
    // Guards the `?cut=` param and any stored barber-page style slug.
    expect(isHairstyleSlug('../../etc/passwd')).toBe(false);
  });
});

// The catalog and public/hair-previews/*.png are generated by two different
// things (this file, and scripts/generate-hair-previews.mjs). Nothing but this
// test stops them drifting — a cut with no art renders an empty bubble.
describe('preview art', () => {
  it('has a PNG for every cut in the catalog', () => {
    const onDisk = new Set(previewSlugsOnDisk());
    const missing = HAIRSTYLES.filter((cut) => !onDisk.has(cut.slug)).map((cut) => cut.slug);
    expect(missing, 'run: node scripts/generate-hair-previews.mjs').toEqual([]);
  });

  it('has no orphan PNGs left behind by a renamed or deleted cut', () => {
    const orphans = previewSlugsOnDisk().filter((slug) => !isHairstyleSlug(slug));
    expect(orphans).toEqual([]);
  });
});
